version: '3'
services:
  mysql:
   container_name: gymsys-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: gymsys
    MYSQL_ROOT_PASSWORD: MyNewPass4!
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3307:3306"
   restart: always

  app:
    container_name: g-mysql
    restart: always
    build: ../gymsys
    working_dir: /gymsys
    volumes:
      - ../gymsys:/gymsys
      - ~/.m2:/root/.m2
      - ~/gymsys/img:/gymsys/img
      - /usr/java/jdk1.8.0_11/jre/lib/security/java.security:/docker-java-home/jre/lib/security/java.security
    ports:
      - "8002:8080"
    depends_on:
      - mysql
    command: mvn spring-boot:run -Dspring-boot.run.profiles=docker